### ISSUE TITLE
Request to transfer ownership to @malaspinsphdev org

### ISSUE THREAD

**Issue by ajhalili2006** [malaspinsphdev/our-swift-sample-codes#2]
Hi, @malaspinsphgithubph! Can you transfer the ownership of this repo to @malaspinsphdev org?

**Comment by RecapTimeSquad** [comment]
Thanks for your request, @AndreiJirohHaliliDev2006! Please wait while we're doing that.

**Comment by RecapTimeSquad** [comment]
Transfer ownership done! So, the case is now officially closed.
